<?php
/**
 * @var $block DK\GoogleTagManager\Block\DataLayer
 */
?>

<script>
    window.dataLayer = window.dataLayer || [];

    <?php
        $data = $block->getJsonDataLayers();
        if (null !== $data): ?>

            window.dataLayerCodes = <?= $block->getCodes() ?>;
            /** @type {Array} */
            let data = <?= /* @escapeNotVerified */ $data ?>;

            if (data.length !== 0) {
                data.forEach((item) => {
                    dataLayer.push(item);
                });
            }
        <?php endif; ?>
</script>