<?php
/**
 * @var $block DK\GoogleTagManager\Block\DataLayer
 */
?>

<script type="text/x-magento-init">
    {
        "*": {
            "DK_GoogleTagManager/js/analyzer": {
                "dataLayer": <?= $block->getJsonDataLayers() ?: '{}' ?>,
                "ajaxUrl": "<?= $block->getAjaxUrl() ?>",
                "currentUrl": "<?= $block->getCurrentUrl() ?>",
                "refererUrl": "<?= $block->getRefererUrl() ?>"
            }
        }
    }
</script>