<?php
/**
 * @var $block DK\GoogleTagManager\Block\DataLayer
 */
?>

<script>
    window.dataLayer = window.dataLayer || [];

    <?php if ($data = $block->getJsonDataLayers()): ?>
        /** @type {Array} */
        let data = <?= /* @escapeNotVerified */ $data ?>;

        if (data.length !== 0) {
            data.forEach((item) => {
                dataLayer.push(item);
            });

        }
    <?php endif; ?>
</script>